### ISSUE TITLE
How to download the dataset

### ISSUE THREAD

**Issue by LLLLLLoki** [dki-lab/GrailQA#11]
The GrailQA dataset cannot be downloaded
![download](https://user-images.githubusercontent.com/30222969/152908646-0fea1eda-0dfe-44da-905e-4d2d4459b11f.png)
.

**Comment by entslscheia** [comment]
Thanks for your interest in our dataset! I think you will need a VPN for that. If you still have trouble with that, let me know and I will try to set up a baiduyun link for you.

**Comment by LLLLLLoki** [comment]
Thanks for your reply.
I have used VPN and FACC1 dataset can not download too.
