### ISSUE TITLE
The time of training is so long

### ISSUE THREAD

**Issue by BitcoinNLPer** [dki-lab/GrailQA#3]
Hi, excuse me, I would like to ask some questions about the time of training for Bert-based KGQA.

When I run your code (BERT+Ranking and BERT+Transduction), the training time is very long (about two months). My machine is (V100, 32g). Do you train for such a long time?  Is there something wrong with me?

thanks for your excellent work and look forward to your reply.

![image](https://user-images.githubusercontent.com/84262181/119696217-8c5e9700-be81-11eb-9db8-c3416d42c030.png)

**Comment by entslscheia** [comment]
Hi,

If it takes around one hour to train one epoch then it is totally fine. It only takes around 5 epochs at most to converge. Please just ignore the estimated training time remaining.  Let me know if you have any other questions!

Best,
Yu

**Comment by BitcoinNLPer** [comment]
Thanks for your reply.

As you can see in the figure, after I train for the first epoch, MRR_k and F1 are still both 0. Is there something wrong? (For migrating from torch1.3 to torch1.7, I modified some codes, e.g., changing tensor type)

Best wishes!

![image](https://user-images.githubusercontent.com/84262181/119700522-e4979800-be85-11eb-8ca6-207ef692c5ce.png)

**Comment by entslscheia** [comment]
F1 and MRR_K are only calculated during validation, so they are both 0 by default during training.

**Comment by BitcoinNLPer** [comment]
Thanks. It's very glad to see such an elaborate and excellent work.
