### ISSUE TITLE
the script of Sparql-to-S-expression

### ISSUE THREAD

**Issue by BitcoinNLPer** [dki-lab/GrailQA#4]
At present, there is no script for the function SPARQL-to-SEXPRESSION in this dir `GrailQA-main/utils/GrailQA-main/utils`. Is it convenient to release it?

Thanks!

**Comment by entslscheia** [comment]
Hi,

We don't actually have the script to convert SPARQL to S-expression. All our S-expressions are converted from graph queries. Sorry about the inconvenience!

**Comment by BitcoinNLPer** [comment]
Ok
