### ISSUE TITLE
Some problem with GrailQA submission

### ISSUE THREAD

**Issue by BitcoinNLPer** [dki-lab/GrailQA#5]
Hello,

I have observed that the prediction results submitted by GrailQA on the test dataset need to be manually reviewed and wait for a week at the latest, which is a bit inconvenient for the iteration of the experiment. Can you provide real-time feedback and evaluation of the test dataset on Codalab as like dev dataset ?

Best

**Comment by entslscheia** [comment]
Hi,

It's to some extent part of the nature of Codalab leaderboard. On my side it's actually just one click thing. Please just email me (gu.826@osu.edu) every time you made a submission. I am normally very responsive and will get back to you very soon.

Best,
Yu

**Comment by BitcoinNLPer** [comment]
Thank you for your meticulous reply, the email has been sent to you, please check it.

Best
