### ISSUE TITLE
`freebase_complete_all_mention` missing

### ISSUE THREAD

**Issue by xiye17** [dki-lab/GrailQA#6]
Hi,
It seems the file for surfaceindexing [freebase_complete_all_mention] at line 133 in entity_linker/bert_entity_linker.py is missing and not included in the downloadable files. Can you possibly release it?

**Comment by xiye17** [comment]
just read the code, nvm. sorry for that.

**Comment by buyaoybz** [comment]
Hi,
I am a newbie, please freebase_complete_all_mention where is this data set?
